#use_frameworks!
platform :ios, '7.0'
inhibit_all_warnings!

target 'WTBookReader' do
pod 'ReactiveCocoa', '~> 2.3.1'
pod 'AFNetworking', '~> 3.1.0'
pod 'SDWebImage', '~> 3.7.1'
pod 'MBProgressHUD', '~> 0.9'
pod 'MJExtension', '~> 2.5.8'
pod 'MJRefresh'
end
